### ISSUE TITLE
Add life-cycle functionality for VMSS (Virtual Machine Scale Sets)

### ISSUE THREAD

**Issue by MarkWarneke** [MarkWarneke/Az.Compute.Lifecycle#3]
Add functions for VMSS (Virtual Machine Scale Sets) e.g. [`Stop-AzVmss`](https://docs.microsoft.com/en-us/powershell/module/az.compute/stop-azvmss?view=azps-5.3.0) and `Start-AzVmss` to the toolkit.

**Comment by AlexanderSehr** [comment]
That's great
